######################################################################
# Automatically generated by qmake (2.01a) mar feb 8 01:01:45 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += EntradaAudio.h Escena.h utilidades.h ventana.h
SOURCES += EntradaAudio.cpp Escena.cpp main.cpp utilidades.cpp ventana.cpp
